Updated test_resourcefile: test_resource_file_delete now works correctly Remaining tests fail due to, I believe, limitations in the API code: get: AttributeError: 'FieldFile' object has no attribute 'resource_file' post/put: rf = self.request.FILES.values()[0] 	  IndexError: list index out of range